name: windows

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2025
    strategy:
      matrix:
        include:
          - build_type: releasedbg
            runtimes: MD
            lto: "n"
          # - build_type: releasedbg
          #   runtimes: MT
          #   lto: "y"

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-windows-${{ matrix.build_type }}-${{ matrix.lto }}
      cancel-in-progress: true

    steps:
      - name: Cleanup Disk Space
        run: |
          Write-Host "Initial Disk Usage:"
          Get-PSDrive C | Select-Object Used, Free
          $paths = @(
              "$env:AGENT_TOOLSDIRECTORY",
              "$env:USERPROFILE\.nuget\packages",
              "C:\ProgramData\Microsoft\VisualStudio\Packages",
              "C:\Microsoft\AndroidSDK",
              "C:\Program Files\Android",
              "C:\Program Files\Java",
              "C:\Program Files\dotnet",
              "C:\Program Files\LLVM",
              "C:\Microsoft\Xamarin",
              "C:\hostedtoolcache\windows\Ruby",
              "C:\hostedtoolcache\windows\Go",
              "C:\usr\local\share\boost",
              "C:\ProgramData\Package Cache"
          )
          foreach ($path in $paths) {
              if (Test-Path $path) {
                  Write-Host "Removing $path..."
                  Remove-Item -Recurse -Force -Path $path -ErrorAction SilentlyContinue
              }
          }
          if (Get-Command docker -ErrorAction SilentlyContinue) {
              Write-Host "Pruning Docker images..."
              docker system prune --all --force --volumes
          }
          $tempPaths = @(
              "$env:TEMP\*",
              "$env:SystemRoot\Temp\*"
          )
          foreach ($temp in $tempPaths) {
              Remove-Item -Recurse -Force $temp -ErrorAction SilentlyContinue
          }
          Write-Host "Final Disk Usage:"
          Get-PSDrive C | Select-Object Used, Free
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.9"
          actions-cache-folder: ".xmake-cache"

      - name: Package
        run: |
          xmake config --yes --verbose --mode=${{ matrix.build_type }} --runtimes=${{ matrix.runtimes }} --policies=build.optimization.lto:${{ matrix.lto }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.build_type }}-${{ matrix.runtimes }}-lto_${{ matrix.lto }}.7z
          path: build/package/*
          compression-level: 0
          if-no-files-found: error